#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask fronius.service >/dev/null
  fi
fi

if [ "$1" = "purge" ]; then
  rm -rf /var/log/thingsplex/fronius
  
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper purge fronius.service >/dev/null
    deb-systemd-helper unmask fronius.service >/dev/null
  fi
fi