#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop fronius.service >/dev/null
  systemctl disable fronius.service || true
  rm /var/log/thingsplex/fronius/* || true
  rm /opt/thingsplex/fronius/data/* || true
fi
